# Generated by Django 3.1.1 on 2023-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nilai',
            field=models.IntegerField(default=0),
        ),
    ]
