# Generated by Django 3.1.1 on 2023-03-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_auto_20230318_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabansiswa',
            name='noSiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.siswa'),
        ),
        migrations.AlterField(
            model_name='jawabansiswa',
            name='noSoal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.kuncijawaban'),
        ),
    ]
